- name: Install openmpi
  package:
    name: openmpi

- name: Install openmpi-devel
  package:
    name: openmpi-devel

- name: add /usr/lib64/openmpi/bin to /home/hpc/.bashrc
  lineinfile:
    path: /home/hpc/.bashrc
    line: export PATH=/usr/lib64/openmpi/bin:$PATH
    owner: hpc
    group: hpc
    mode: 0744