- name: Install openmpi
  package:
    name: openmpi

- name: Install openmpi-devel
  package:
    name: openmpi-devel

- name: add /usr/lib64/openmpi/bin to /etc/profile
  lineinfile:
    path: /etc/profile
    line: export PATH=/usr/lib64/openmpi/bin:$PATH