# This is a community role and can be installed using: ansible-galaxy collection install community.general
- name: Create an xfs filesystem on a drive
  community.general.filesystem:
    fstype: xfs
    dev: "{{VOLUME}}"