- name: Add APT signing key for Helm
  apt_key:
    url: https://helm.baltorepo.com/organization/signing.asc
    state: present

- name: Install apt-transport-https
  apt:
    name: apt-transport-https

# Add Helm repo into sources list.
- apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Run apt update
  apt:
    update_cache: yes

- name: Install Helm
  apt:
    name: helm