- name: Create a mountable directory if it does not exist
      file:
        path: /mnt/share
        state: directory
        owner: root
        group: root
        mode: '0777'

#This is a third party module, and can be installed using: ansible-galaxy collection install ansible.posix
- name: Mount an NFS volume
  ansible.posix.mount:
    src: "{{MANAGER_IP}}":/mnt/share
    path: /mnt/share
    opts: rw,sync,hard,intr
    state: mounted
    fstype: nfs

