- name: Download and unzip Terraform 13 to /usr/local/bin
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.13.0-beta3/terraform_0.13.0-beta3_linux_amd64.zip
    dest: /tmp
    remote_src: yes

- name: Copy Terraform beta from /tmp and rename it
    copy:
      src: /tmp/terraform
      dest: /usr/local/bin/terraform13
      remote_src: yes