- name: Create k8s namespace "jenkins"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: jenkins
    state: present

- name: Create Hetzner API token
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: hetzner
        namespace: jenkins
        labels:
          "jenkins.io/credentials-type": "secretText"
        annotations:
          "jenkins.io/credentials-description" : "Hetzner API token"
      type: Opaque
      stringData:
        text: "{{ hetzner_api }}"

- name: Create Ansible Vault password
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ansible-vault
        namespace: jenkins
        labels:
          "jenkins.io/credentials-type": "secretText"
        annotations:
          "jenkins.io/credentials-description" : "Ansible Vault password"
      type: Opaque
      stringData:
        text: "{{ ansible_vault }}"

- name: Create AWS credentials file
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: aws-andy
        namespace: jenkins
        labels:
          "jenkins.io/credentials-type": "secretFile"
        annotations:
          "jenkins.io/credentials-description" : "AWS credentials file"
      type: Opaque
      stringData:
        filename: aws-andy
      data:
        data: "{{ aws_andy }}"

- name: Create Dockerhub password
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: dockerhub
        namespace: jenkins
        labels:
          "jenkins.io/credentials-type": "secretText"
        annotations:
          "jenkins.io/credentials-description" : "Dockerhub password"
      type: Opaque
      stringData:
        text: "{{ dockerhub }}"

- name: Copy hetzner-ssh manifest to /tmp
  copy:
    src: hetzner-ssh.yaml
    dest: /tmp/hetzner-ssh.yaml
    decrypt: yes
    mode: '0664'

- name: Apply hetzner-ssh secret
  kubernetes.core.k8s:
    state: present
    src: /tmp/hetzner-ssh.yaml
    namespace: jenkins

- name: Copy github-ssh manifest to /tmp
  copy:
    src: github-ssh.yaml
    dest: /tmp/github-ssh.yaml
    decrypt: yes
    mode: '0664'

- name: Apply github-ssh secret
  kubernetes.core.k8s:
    state: present
    src: /tmp/github-ssh.yaml
    namespace: jenkins
        