- name: Download Helm tar.gz
  get_url:
    url: https://get.helm.sh/helm-v3.5.0-linux-arm.tar.gz
    dest: /tmp
    mode: '0777'

- name: Un tar helm to /usr/local/bin
  shell: "cd /tmp && tar xvf helm-v3.5.0-linux-arm.tar.gz -C /usr/local/bin" --strip-components 2