- name: Install dependencies
  package:
    name: 
      - bash
      - coreutils
      - curl
      - git
      - git-lfs
      - openssh-client
      - tini
      - ttf-dejavu
      - tzdata
      - unzip

- name: Add group jenkins
  ansible.builtin.group:
    name: jenkins
    gid: 1000
    state: present

- name: Add user jenkins
  user:
    name: jenkins
    comment: jenkins
    uid: 1000
    group: jenkins

- name: Create folder /var/jenkins_home
  file:
     path: /var/jenkins_home
     state: directory
     owner: jenkins
     group: jenkins
     mode: '700'

- name: Create folder /usr/share/jenkins
  file:
     path: /usr/share/jenkins
     state: directory
     owner: root
     group: root
     mode: '0777'

- name: Create folder /usr/share/jenkins/ref
  file:
     path: /usr/share/jenkins/ref
     state: directory
     owner: root
     group: root
     mode: '0777'

- name: Copy a jenkins war to /usr/share/jenkins
  get_url:
    url: https://get.jenkins.io/war/{{JENKINS_VERSION}}/jenkins.war
    dest: /usr/share/jenkins
    mode: '0777'

- name: Copy jenkins-support to /usr/local/bin/jenkins-support
  copy:
    src: jenkins-support
    dest: /usr/local/bin/jenkins-support
    mode: 0777

- name: Copy jenkins.sh to /usr/local/bin/jenkins.sh
  copy:
    src: jenkins.sh
    dest: /usr/local/bin/jenkins.sh
    mode: 0777

#- name: Copy tini-shim.sh to /bin/tini
#  copy: 
#    src: tini-shim.sh
#    dest: /sbin/tini
#    mode: 0777
