- name: download swarm jar
  get_url:
    url: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.23/swarm-client-3.23.jar
    dest: /usr/local/bin/swarm-client.jar

- name: add env var for swarm
  lineinfile:
    path: /etc/profile
    line: export SWARM="{{ andy }}"

- name: Copy swarm.sh to /usr/local/bin
  copy:
    src: swarm.sh
    dest: /usr/local/bin
    mode: 0777
#Add swarm.sh to cron
- cron:
    name: "add swarm.sh to cron"
    special_time: reboot
    job: "/usr/local/bin/swarm.sh"