- name: Create a mountable directory if it does not exist
  file:
    path: /mnt/share
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Mount a volume
  ansible.posix.mount:
    path: /mnt/share
    src: "{{VOLUME}}"
    fstype: xfs
    opts: rw,sync,hard,intr
    state: mounted