# docker buildx build --platform linux/amd64,linux/arm64 --progress=plain --push -t calmmopey/worker .

ARG TAG
FROM jenkins/jenkins:${TAG} AS base
ENV CASC_JENKINS_CONFIG /usr/share/jenkins/casc.yaml
RUN echo "This stage is used on all architectures"
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/plugins.txt
COPY casc.yaml /usr/share/jenkins/casc.yaml