# docker buildx build --platform linux/amd64,linux/arm64/v8 --progress=plain --push -t calmmopey/terratest .

ARG TAG
FROM golang:${TAG} AS base
RUN echo "This stage is used on all architectures"
RUN apt-get update

# arm64-specific stage
FROM base AS build-arm64
ARG TF_VER
RUN echo "This stage is used on arm64"
RUN	apt-get install zip unzip -y \
    && apt-get autoclean \
	&& apt-get autoremove \
    && wget https://releases.hashicorp.com/terraform/${TF_VER}/terraform_${TF_VER}_linux_arm64.zip \
    && unzip terraform_${TF_VER}_linux_arm64.zip \
    && cp terraform /usr/local/bin \
    && rm terraform_${TF_VER}_linux_arm64.zip

# amd64-specific stage
FROM base AS build-amd64
ARG TF_VER
RUN echo "This stage is used on amd64 (x86)"
RUN apt-get install zip unzip -y \
    && apt-get autoclean \
	&& apt-get autoremove \
    && wget https://releases.hashicorp.com/terraform/${TF_VER}/terraform_${TF_VER}_linux_amd64.zip \
    && unzip terraform_${TF_VER}_linux_amd64.zip \
    && cp terraform /usr/local/bin \
    && rm terraform_${TF_VER}_linux_amd64.zip