# docker buildx build --platform linux/amd64,linux/arm64 --progress=plain --push -t calmmopey/terratest .

ARG TAG
ARG TF_VER
FROM --platform=linux/amd64 golang:$TAG as stage-amd64
RUN apt-get install zip unzip -y \
    && apt-get autoclean \
	&& apt-get autoremove \
    && wget https://releases.hashicorp.com/terraform/$TF_VER/terraform_$TF_VER_linux_amd64.zip \
    && unzip terraform_$TF_VER_linux_amd64.zip \
    && cp terraform /usr/local/bin \
    && rm terraform_$TF_VER_linux_amd64.zip \
    && echo ${TF_VER}

#ARG TAG
#ARG TF_VER
#FROM --platform=linux/amd64 golang:${TAG} as stage-arm64
#RUN apt-get install zip unzip -y \
#    && apt-get autoclean \
#	&& apt-get autoremove \
#    && wget https://releases.hashicorp.com/terraform/${TF_VER}/terraform_${TF_VER}_linux_arm64.zip \
#    && unzip terraform_${TF_VER}_linux_arm64.zip \
#    && cp terraform /usr/local/bin \
#    && rm terraform_${TF_VER}_linux_arm64.zip