- name: Download kubectl to /usr/localbin and make it executable
  ansible.builtin.copy:
    src: https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin
    remote_src: yes
    mode: '0777'
