- name: Download cert-manager manifest to /tmp.
  ansible.builtin.get_url:
    url: https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml
    dest: /tmp/cert-manager.yaml
    mode: '0664'

- name: Apply cert-manager manifest to the cluster.
  kubernetes.core.k8s:
    state: present
    src: /tmp/cert-manager.yaml