- name: Download and unzip Terraform to /usr/local/bin
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_arm.zip
    dest: /usr/local/bin
    remote_src: yes