- name: sudo sed -i 's:#\(http_access allow localnet\):\1:' /etc/squid/squid.conf
  shell: sudo sed -i 's:#\(http_access allow localnet\):\1:' /etc/squid/squid.conf

- name: sudo sed -i 's:#\(http_access deny to_localhost\):\1:' /etc/squid/squid.conf
  shell: sudo sed -i 's:#\(http_access deny to_localhost\):\1:' /etc/squid/squid.conf

- name: sudo sed -i 's:#\(acl localnet src 10.0.0.0/8.*\):\1:' /etc/squid/squid.conf
  shell: sudo sed -i 's:#\(acl localnet src 10.0.0.0/8.*\):\1:' /etc/squid/squid.conf

- name: sudo sed -i 's:#\(acl localnet src 172.16.0.0/12.*\):\1:' /etc/squid/squid.conf
  shell: sudo sed -i 's:#\(acl localnet src 172.16.0.0/12.*\):\1:' /etc/squid/squid.conf

- name: sudo sed -i 's:#\(acl localnet src 192.168.0.0/16.*\):\1:' /etc/squid/squid.conf
  shell: sudo sed -i 's:#\(acl localnet src 192.168.0.0/16.*\):\1:' /etc/squid/squid.conf

- name: sudo sed -i 's:#\(acl localnet src fc00\:\:/7.*\):\1:' /etc/squid/squid.conf
  shell: sudo sed -i 's:#\(acl localnet src fc00\:\:/7.*\):\1:' /etc/squid/squid.conf

- name: sudo sed -i 's:#\(acl localnet src fe80\:\:/10.*\):\1:' /etc/squid/squid.conf
  shell: sudo sed -i 's:#\(acl localnet src fe80\:\:/10.*\):\1:' /etc/squid/squid.conf
  
- name: Insert a text block into /etc/squid/squid.conf
  blockinfile:
    path: /etc/squid/squid.conf
    block: |
      acl to_metadata dst 169.254.169.254
      http_access deny to_metadata