---
- hosts: all
  roles:
  - role: install-zip
  - role: install-unzip
  - role: install-java-alpine
  - role: install-ansible-apk
  - role: install-terraform
  - role: install-packer-1.3.5
  - role: install-openrc-apk
  - role: install-docker-apk
  - role: install-git
