- name: Download and untar Quantum Espresso to /mnt/share
  unarchive:
    src: https://github.com/QEF/q-e/releases/download/qe-6.7.0/qe-6.7-ReleasePack.tgz
    dest: /mnt/share
    remote_src: yes

- name: Configure QE
  shell: ./configure
  args:
    chdir: /mnt/share/qe-6.7

- name: Make pw
  shell: make pw
  args:
    chdir: /mnt/share/qe-6.7

- name: Git checkout QE benchmarks to /mnt/share
  git:
    repo: 'https://github.com/QEF/benchmarks.git'
    dest: /mnt/share

- name: Copy para-speedup.sh to /mnt/share/benchmarks/small-benchmarks
  copy:
    src: para-speedup.sh
    dest: /mnt/share/benchmarks/small-benchmarks
    mode: 0777

- name: Copy pwscf_bench.sh to /mnt/share/benchmarks/small-benchmarks
  copy:
    src: pwscf_bench.sh
    dest: /mnt/share/benchmarks/small-benchmarks
    mode: 0777