- name: Copy proxy.sh to /etc/profile.d
  copy:
    src: proxy.sh
    dest: /etc/profile.d/proxy.sh
    owner: root
    group: root
    mode: a+x

- name: Add Defaults env_keep += \"ftp_proxy http_proxy https_proxy no_proxy" to /etc/sudoers
  lineinfile:
    path: /etc/sudoers
    line: Defaults env_keep += \"ftp_proxy http_proxy https_proxy no_proxy"
    create: yes
    mode: '440'