- name: Insert a text block into /etc/profile
  blockinfile:
    path: /etc/profile
    block: |
      export http_proxy="http://squid.us-central1-a.c.jenkins-test-project-284609.internal:3128"
      export https_proxy="http://squid.us-central1-a.c.jenkins-test-project-284609.internal:3128"
      export ftp_proxy="http://squid.us-central1-a.c.jenkins-test-project-284609.internal:3128"
      export no_proxy=169.254.169.254,metadata,metadata.google.internal

- name: cp /etc/sudoers /tmp/sudoers.new
  shell: cp /etc/sudoers /tmp/sudoers.new

- name: chmod 640 /tmp/sudoers.new
  shell: chmod 640 /tmp/sudoers.new

- name: echo "Defaults env_keep += \"ftp_proxy http_proxy https_proxy no_proxy"\" >>/tmp/sudoers.new
  shell: echo "Defaults env_keep += \"ftp_proxy http_proxy https_proxy no_proxy"\" >>/tmp/sudoers.new

- name: chmod 440 /tmp/sudoers.new
  shell: chmod 440 /tmp/sudoers.new

- name: visudo -c -f /tmp/sudoers.new && cp /tmp/sudoers.new /etc/sudoers
  shell: visudo -c -f /tmp/sudoers.new && cp /tmp/sudoers.new /etc/sudoers