- name: Copy proxy.sh to /etc/profile.d
  copy:
    src: proxy.sh
    dest: /etc/profile.d/proxy.sh
    owner: root
    group: root
    mode: a+x

- name: cp /etc/sudoers /tmp/sudoers.new
  shell: cp /etc/sudoers /tmp/sudoers.new

- name: chmod 640 /tmp/sudoers.new
  shell: chmod 640 /tmp/sudoers.new

- name: echo "Defaults env_keep += \"ftp_proxy http_proxy https_proxy no_proxy"\" >>/tmp/sudoers.new
  shell: echo "Defaults env_keep += \"ftp_proxy http_proxy https_proxy no_proxy"\" >>/tmp/sudoers.new

- name: chmod 440 /tmp/sudoers.new
  shell: chmod 440 /tmp/sudoers.new

- name: visudo -c -f /tmp/sudoers.new && cp /tmp/sudoers.new /etc/sudoers
  shell: visudo -c -f /tmp/sudoers.new && cp /tmp/sudoers.new /etc/sudoers