- name: Add APT signing key for Jenkins
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

# Add Jenkins repo into sources list.
- apt_repository:
    repo: http://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Run apt update
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
