- name: Download and unzip Packer to /usr/local/bin
  unarchive:
    src: https://releases.hashicorp.com/packer/1.3.5/packer_1.3.5_linux_amd64.zip
    dest: /tmp
    remote_src: yes

- name: Copy Packer 1.3.5 from /tmp and rename it
  copy:
    src: /tmp/packer
    dest: /usr/local/bin/packer135
    remote_src: yes
    mode: preserve